# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Jordan Walsh
tagline:          "Jordan's Developer Portfolio and Blog"
description:      "A software <a href='https://www.linkedin.com/in/jordancwalshsoftwaredeveloper/' target='_blank'>developer</a> and tutorial writer, merging his technical skills with clear communication. Find him on twitter <a href='https://twitter.com/JCWsoftwareDev' target='_blank'>@JCWsoftwareDev</a>."
url:              http://localhost:4000/
baseurl:          /

author:
  name:           'Jordan C Walsh'
  url:            https://twitter.com/JCWsoftwareDev

paginate:         1

# Custom var
version:		  1.0.1

github:
  repo:           https://github.com/JordanCWalsh/JordanCWalsh.GitHub.io

# Gems
gems:
  - jekyll-paginate