# Dependencies
markdown: redcarpet
highlighter: rouge

# Permalinks
permalink: pretty
#relative_permalinks: true

# Setup
title: Jordan C W
tagline: "Jordan's Software Engineering Blog"
description: "A <a href='https://www.linkedin.com/in/jordancwalsh/' target='_blank'>software developer</a> and tutorial writer, merging technical know-how with proactive communication. Find him on twitter <a href='https://twitter.com/JCWsoftwareDev' target='_blank'>@JCWsoftwareDev</a>."
url: http://localhost:4000/
baseurl: /

author:
  name: "Jordan C Walsh"
  url: https://twitter.com/JCWsoftwareDev

paginate: 1

# Custom var
version: 1.1.0

github:
  repo: https://github.com/JordanCWalsh/JordanCWalsh.GitHub.io

# Gems
gems:
  - jekyll-paginate
